const READING_KEY="mf-reading-v1", LEARNED_KEY="mf-learned-vocab-v1";
let readings=MF.read(READING_KEY,[]), vocabulary=[], openReading="";
const cards=document.querySelector("#readingCards"), detail=document.querySelector("#readingDetail"), dialog=document.querySelector("#readingDialog"), popup=document.querySelector("#vocabPopup");
const learned=new Set(MF.read(LEARNED_KEY,[]));

function renderCards(){cards.replaceChildren();readings.forEach((item,index)=>{const card=MF.el("article","library-card");card.append(MF.el("span","number-badge",String(index+1).padStart(2,"0")),MF.el("h3","",item.title),MF.el("p","",item.topic||"Chưa có chủ đề"),MF.el("small","",`${item.level} • ${item.date||"Chưa có ngày"} • ${item.content.trim().split(/\s+/).filter(Boolean).length} từ`));const state=MF.el("span",item.done?"state done-state":"state",item.done?"✓ Đã đọc":"○ Chưa đọc");const actions=MF.el("div","card-actions");[["Mở bài đọc","open"],["Sửa","edit"],["Xóa","delete"]].forEach(([label,action])=>{const b=MF.el("button","",label);b.dataset.action=action;b.dataset.id=item.id;actions.append(b);});card.append(state,actions);cards.append(card);});const add=MF.el("button","add-card","＋\nThêm bài đọc");add.onclick=()=>openForm();cards.append(add);}

function highlightCandidates(){const candidates=[];const seen=new Set();for(const entry of vocabulary){const parts=[entry.word,...entry.word.match(/[\p{L}À-ÿ]+(?:['’][\p{L}À-ÿ]+)?/gu)||[]];for(const part of parts){const match=part.trim();const key=match.toLocaleLowerCase("fr");if(key.length<2||seen.has(key))continue;seen.add(key);candidates.push({match,entry});}}return candidates.sort((a,b)=>b.match.length-a.match.length);}
function highlightedText(text){const wrapper=MF.el("div","article-text"),candidates=highlightCandidates(),lower=text.toLocaleLowerCase("fr");let position=0,plainStart=0;const isLetter=char=>char&&/\p{L}/u.test(char);while(position<text.length){let found=null;for(const candidate of candidates){const target=candidate.match.toLocaleLowerCase("fr");if(lower.slice(position,position+target.length)!==target)continue;const before=text[position-1],after=text[position+target.length];if(isLetter(before)||isLetter(after))continue;found=candidate;break;}if(!found){position++;continue;}if(position>plainStart)wrapper.append(document.createTextNode(text.slice(plainStart,position)));const word=found.entry,matchedText=text.slice(position,position+found.match.length);const mark=MF.el("button",learned.has(word.word)?"vocab-mark learned":"vocab-mark",matchedText);mark.type="button";mark.onclick=event=>showVocab(word,event.currentTarget);wrapper.append(mark);position+=found.match.length;plainStart=position;}if(plainStart<text.length)wrapper.append(document.createTextNode(text.slice(plainStart)));return wrapper;}

function showVocab(word,target){popup.replaceChildren();const close=MF.el("button","popup-close","×");close.onclick=()=>popup.hidden=true;const speak=MF.el("button","","🔊 Phát âm");speak.onclick=()=>MF.speak(`${word.word}. ${word.example||""}`);const learn=MF.el("button",learned.has(word.word)?"primary":"",learned.has(word.word)?"✓ Đã thuộc":"Đánh dấu đã thuộc");learn.onclick=()=>{if(learned.has(word.word))learned.delete(word.word);else learned.add(word.word);MF.write(LEARNED_KEY,[...learned]);popup.hidden=true;showReading(openReading);};popup.append(close,MF.el("h3","",word.word),MF.el("b","",word.meaning||"Chưa có nghĩa"),MF.el("p","",word.example||"Chưa có ví dụ"),MF.el("small","",word.date?`Ngày: ${word.date}`:""),speak,learn);const rect=target.getBoundingClientRect();popup.style.left=`${Math.min(window.innerWidth-330,Math.max(10,rect.left))}px`;popup.style.top=`${Math.min(window.innerHeight-250,rect.bottom+8)}px`;popup.hidden=false;}

function showReading(id){const item=readings.find(x=>x.id===id);if(!item)return;openReading=id;detail.hidden=false;detail.replaceChildren();const close=MF.el("button","detail-close","×");close.onclick=()=>{detail.hidden=true;popup.hidden=true;};const top=MF.el("div","detail-heading");top.append(MF.el("div","","") ,MF.el("h2","",item.title));top.firstChild.append(MF.el("span","level-badge",item.level),MF.el("span","",item.topic||""));const article=highlightedText(item.content);const notes=MF.el("section","lesson-box");notes.append(MF.el("h3","","Ghi chú"),MF.el("p","preline",item.notes||"Chưa có ghi chú."));const questions=MF.el("section","exercise-list");questions.append(MF.el("h3","",`Câu hỏi (${item.questions.length})`));item.questions.forEach((q,i)=>{const row=MF.el("details","question-item");const summary=MF.el("summary","",`${i+1}. ${q}`);row.append(summary,MF.el("p","",item.answers[i]||"Chưa có đáp án"));questions.append(row);});const controls=MF.el("div","resource-links");const done=MF.el("button","primary",item.done?"✓ Đã đọc":"Đánh dấu đã đọc");done.onclick=()=>{item.done=!item.done;save();};controls.append(done);if(item.link){const link=MF.el("button","","Mở nguồn ↗");link.onclick=()=>MF.openUrl(item.link);controls.append(link);}const idx=readings.indexOf(item);if(idx>0){const prev=MF.el("button","","← Bài trước");prev.onclick=()=>showReading(readings[idx-1].id);controls.append(prev);}if(idx<readings.length-1){const next=MF.el("button","","Bài tiếp →");next.onclick=()=>showReading(readings[idx+1].id);controls.append(next);}detail.append(close,top,article,notes,questions,controls);detail.scrollIntoView({behavior:"smooth"});}

function openForm(item=null){document.querySelector("#readingId").value=item?.id||"";document.querySelector("#readingTitle").value=item?.title||"";document.querySelector("#readingTopic").value=item?.topic||"";document.querySelector("#readingLevel").value=item?.level||"B1";document.querySelector("#readingDate").value=item?.date||"";document.querySelector("#readingContent").value=item?.content||"";document.querySelector("#readingSource").value=item?.source||"";document.querySelector("#readingLink").value=item?.link||"";document.querySelector("#readingQuestions").value=(item?.questions||[]).join("\n");document.querySelector("#readingAnswers").value=(item?.answers||[]).join("\n");document.querySelector("#readingNotes").value=item?.notes||"";dialog.showModal();}
const lines=id=>document.querySelector(id).value.split("\n").map(x=>x.trim()).filter(Boolean);function save(){MF.write(READING_KEY,readings);if(window.MFStore)MFStore.set("readings",readings);renderCards();if(openReading)showReading(openReading);}
async function loadVocab(){try{vocabulary=await MF.fetchVocabulary();if(openReading)showReading(openReading);}catch(_){MF.toast("Không thể tải từ vựng T6. Hãy kiểm tra quyền chia sẻ Google Sheets");}}
document.querySelector("#readingForm").onsubmit=event=>{event.preventDefault();const id=document.querySelector("#readingId").value||MF.uid("reading"),title=document.querySelector("#readingTitle").value.trim(),content=document.querySelector("#readingContent").value.trim();if(!title||!content)return MF.toast("Hãy nhập tên và nội dung bài đọc");const old=readings.find(x=>x.id===id);const item={id,title,content,topic:document.querySelector("#readingTopic").value.trim(),level:document.querySelector("#readingLevel").value,date:document.querySelector("#readingDate").value,source:document.querySelector("#readingSource").value.trim(),link:MF.validUrl(document.querySelector("#readingLink").value),questions:lines("#readingQuestions"),answers:lines("#readingAnswers"),notes:document.querySelector("#readingNotes").value.trim(),done:old?.done||false};const index=readings.findIndex(x=>x.id===id);if(index>=0)readings[index]=item;else readings.push(item);save();dialog.close();MF.toast("Đã lưu bài đọc");};cards.onclick=event=>{const b=event.target.closest("button[data-action]");if(!b)return;const item=readings.find(x=>x.id===b.dataset.id);if(b.dataset.action==="open")showReading(item.id);if(b.dataset.action==="edit")openForm(item);if(b.dataset.action==="delete"&&confirm(`Xóa “${item.title}”?`)){readings=readings.filter(x=>x.id!==item.id);detail.hidden=true;save();}};document.querySelector("#addReading").onclick=()=>openForm();document.querySelector("[data-close]").onclick=()=>dialog.close();renderCards();loadVocab();
