const READING_KEY="mf-reading-v1",LEARNED_KEY="mf-learned-vocab-v1";
const $=selector=>document.querySelector(selector),today=()=>new Date().toISOString().slice(0,10),clone=value=>JSON.parse(JSON.stringify(value));
const defaults={topic:"",level:"B1",content:"",source:"",link:"",date:"",estimatedMinutes:6,notes:"",summary:"",tags:[],savedVocabulary:[],savedStructures:[],questions:[],answers:[],explanations:[],readingSeconds:0,progress:0,completed:false,completedAt:"",lastOpenedAt:"",score:0,favorite:false,questionResults:[]};
let readings=(MFStore.list("readings").length?MFStore.list("readings"):MF.read(READING_KEY,[])).map(normalizeReading),vocabulary=[],openReading="",timer=null,timerRunning=false,fontSize=18,highlightOn=true;
const cards=$("#readingCards"),library=$("#readingLibrary"),workspace=$("#readingWorkspace"),article=$("#readingArticle"),dialog=$("#readingDialog"),popup=$("#vocabPopup"),learned=new Set(MF.read(LEARNED_KEY,[]));

function normalizeReading(item){const value={...clone(defaults),...item};value.completed=Boolean(item.completed??item.done);value.done=value.completed;value.estimatedMinutes=Number(value.estimatedMinutes)||6;value.readingSeconds=Number(value.readingSeconds)||0;value.tags=Array.isArray(value.tags)?value.tags:[];value.savedVocabulary=Array.isArray(value.savedVocabulary)?value.savedVocabulary:[];value.savedStructures=Array.isArray(value.savedStructures)?value.savedStructures:[];value.questions=Array.isArray(value.questions)?value.questions:[];value.answers=Array.isArray(value.answers)?value.answers:[];value.explanations=Array.isArray(value.explanations)?value.explanations:[];value.questionResults=Array.isArray(value.questionResults)?value.questionResults:[];return value;}
function current(){return readings.find(item=>item.id===openReading);}
function wordCount(text){return String(text||"").trim().split(/\s+/).filter(Boolean).length;}
function save(render=true){MF.write(READING_KEY,readings);MFStore.set("readings",readings);if(render)renderCards();}
function fmt(seconds){return `${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;}
function updateTimer(){const item=current();if(!item)return;$("#readingTimer").textContent=fmt(item.readingSeconds);const estimate=item.estimatedMinutes*60;item.progress=Math.min(item.completed?100:99,Math.round(item.readingSeconds/estimate*100));$("#readingProgressBar").style.width=`${item.completed?100:item.progress}%`;$("#readingProgressText").textContent=`${item.completed?100:item.progress}%`;}
function stopTimer(){clearInterval(timer);timer=null;timerRunning=false;$("#timerToggle").textContent="▶";if(current())save(false);}
function toggleTimer(){if(timerRunning)return stopTimer();timerRunning=true;$("#timerToggle").textContent="Ⅱ";timer=setInterval(()=>{const item=current();if(!item)return stopTimer();item.readingSeconds++;updateTimer();if(item.readingSeconds%10===0)save(false);},1000);}

function renderCards(){cards.replaceChildren();readings.forEach((item,index)=>{const card=MF.el("article","library-card reading-library-card");const score=item.questionResults.length?`${item.score}% gần nhất`:"Chưa làm câu hỏi";card.append(MF.el("span","number-badge",String(index+1).padStart(2,"0")),MF.el("button","favorite-button",item.favorite?"★":"☆"),MF.el("h3","",item.title),MF.el("p","",item.topic||"Chưa có chủ đề"),MF.el("small","",`${item.level} • ${wordCount(item.content)} từ • ${item.estimatedMinutes} phút`),MF.el("small","",score),MF.el("span",item.completed?"state done-state":"state",item.completed?"✓ Đã đọc":"○ Chưa đọc"));card.querySelector(".favorite-button").onclick=()=>{item.favorite=!item.favorite;save();};const actions=MF.el("div","card-actions");[["Mở bài đọc","open"],["Sửa","edit"],["Sao chép","copy"],["Xóa","delete"]].forEach(([label,action])=>{const button=MF.el("button","",label);button.dataset.action=action;button.dataset.id=item.id;actions.append(button);});card.append(actions);cards.append(card);});const add=MF.el("button","add-card","＋\nThêm bài đọc");add.onclick=()=>openForm();cards.append(add);}

function highlightCandidates(){const candidates=[],seen=new Set();for(const entry of vocabulary){const full=String(entry.word||"").trim(),parts=full.match(/[\p{L}À-ÿ]+(?:['’][\p{L}À-ÿ]+)?/gu)||[];for(const match of [full,...parts]){const key=match.toLocaleLowerCase("fr");if(key.length<2||seen.has(key))continue;seen.add(key);candidates.push({match,entry});}}return candidates.sort((a,b)=>b.match.length-a.match.length);}
function highlightedText(text){const wrapper=MF.el("div","article-text"),candidates=highlightOn?highlightCandidates():[],lower=text.toLocaleLowerCase("fr");let position=0,plainStart=0;const isLetter=char=>char&&/\p{L}/u.test(char);while(position<text.length){let found=null;for(const candidate of candidates){const target=candidate.match.toLocaleLowerCase("fr");if(lower.slice(position,position+target.length)!==target)continue;if(isLetter(text[position-1])||isLetter(text[position+target.length]))continue;found=candidate;break;}if(!found){position++;continue;}if(position>plainStart)wrapper.append(document.createTextNode(text.slice(plainStart,position)));const matched=text.slice(position,position+found.match.length),mark=MF.el("button",learned.has(found.entry.word)?"vocab-mark learned":"vocab-mark",matched);mark.type="button";mark.setAttribute("aria-label",`Xem nghĩa ${matched}`);mark.onclick=event=>showVocab(found.entry,event.currentTarget);wrapper.append(mark);position+=found.match.length;plainStart=position;}if(plainStart<text.length)wrapper.append(document.createTextNode(text.slice(plainStart)));return wrapper;}
function storeVocabulary(word){const item=current();if(!item)return;if(!item.savedVocabulary.some(value=>value.word===word.word))item.savedVocabulary.push({...word,mastery:Number(word.mastery)||0});save(false);renderSavedVocabulary();MF.toast("Đã thêm vào ghi chú từ vựng");}
function setMastery(word,level){const central=MFStore.list("vocabulary"),key=String(word.word).toLocaleLowerCase("fr"),index=central.findIndex(item=>String(item.word).toLocaleLowerCase("fr")===key);const patch={...word,mastery:level,lastReviewedAt:new Date().toISOString(),nextReviewAt:new Date(Date.now()+[0,1,3,7,21][level-1]*86400000).toISOString().slice(0,10)};if(index>=0)central[index]={...central[index],...patch};else central.push({...patch,id:word.id||MF.uid("vocab")});MFStore.set("vocabulary",central);word.mastery=level;storeVocabulary(word);popup.hidden=true;}
function showVocab(word,target){popup.replaceChildren();const close=MF.el("button","popup-close","×");close.setAttribute("aria-label","Đóng thẻ từ");close.onclick=()=>popup.hidden=true;const speak=MF.el("button","","🔊 Phát âm");speak.onclick=()=>MF.speak(`${word.word}. ${word.example||""}`);const add=MF.el("button","primary","＋ Thêm vào ghi chú");add.onclick=()=>storeVocabulary(word);const error=MF.el("button","","🧩 Đưa vào Sổ lỗi");error.onclick=()=>{MFStore.add("errors",{skill:"CE",type:"Từ vựng",source:current()?.title||"Bài đọc",context:word.example||word.word,original:word.word,corrected:word.meaning,explanation:"Ôn lại từ vựng trong ngữ cảnh.",date:today(),reviewDate:today(),level:1,resolved:false,reviewCount:0});MF.toast("Đã thêm vào Sổ lỗi");};const levels=MF.el("div","popup-levels");for(let i=1;i<=5;i++){const button=MF.el("button",Number(word.mastery)===i?"active":"",String(i));button.title=["Chưa nhớ","Hơi nhớ","Đang thuộc","Gần thuộc","Đã thuộc"][i-1];button.onclick=()=>setMastery(word,i);levels.append(button);}popup.append(close,MF.el("small","",word.partOfSpeech||"Từ vựng T6"),MF.el("h3","",word.word),MF.el("b","",word.meaning||"Chưa có nghĩa"),MF.el("p","",word.example||"Chưa có ví dụ"),speak,add,MF.el("small","","Mức độ thuộc"),levels,error);const rect=target.getBoundingClientRect(),width=340;popup.style.left=`${Math.min(window.innerWidth-width-10,Math.max(10,rect.left))}px`;popup.style.top=`${Math.min(window.innerHeight-popup.offsetHeight-20,rect.bottom+8)}px`;popup.hidden=false;}

function parseQuestion(raw,index,item){if(typeof raw==="object")return raw;const [text,type="short",options=""]=String(raw).split("|");return{text,type:type.trim().toLowerCase(),options:options?options.split(";").map(x=>x.trim()).filter(Boolean):[],answer:item.answers[index]||"",explanation:item.explanations[index]||""};}
function renderQuestions(item){const section=MF.el("details","reading-questions");const heading=MF.el("summary","",`📋 Câu hỏi đọc hiểu (${item.questions.length})`);const body=MF.el("div","question-workspace");section.append(heading,body);if(!item.questions.length)body.append(MF.el("p","empty-state","Bài đọc chưa có câu hỏi."));item.questions.forEach((raw,index)=>{const q=parseQuestion(raw,index,item),box=MF.el("section","question-box"),title=MF.el("h4","",`${index+1}. ${q.text}`),answerWrap=MF.el("div","question-answer");let input;if(["mcq","trắc nghiệm","truefalse","đúng/sai"].includes(q.type)){const choices=q.options.length?q.options:["Đúng","Sai"];choices.forEach(choice=>{const label=MF.el("label");input=document.createElement("input");input.type="radio";input.name=`q-${index}`;input.value=choice;label.append(input,document.createTextNode(choice));answerWrap.append(label);});}else{input=document.createElement(q.type.includes("short")||q.type.includes("ngắn")?"textarea":"input");input.placeholder="Nhập câu trả lời…";answerWrap.append(input);}const feedback=MF.el("div","question-feedback");const check=MF.el("button","primary","Kiểm tra đáp án");check.onclick=()=>{const radio=answerWrap.querySelector('input[type="radio"]'),chosen=radio?(answerWrap.querySelector("input:checked")?.value||""):(answerWrap.querySelector("textarea,input")?.value||"");if(!chosen)return MF.toast("Hãy nhập hoặc chọn câu trả lời");const clean=value=>String(value).trim().toLocaleLowerCase("fr");const correct=clean(chosen)===clean(q.answer);feedback.className=`question-feedback ${correct?"correct":"wrong"}`;feedback.textContent=correct?`✓ Chính xác. ${q.explanation}`:`✗ Đáp án: ${q.answer}. ${q.explanation}`;item.questionResults[index]={answer:chosen,correct,answeredAt:new Date().toISOString()};const answered=item.questionResults.filter(Boolean),right=answered.filter(x=>x.correct).length;item.score=answered.length?Math.round(right/answered.length*100):0;save(false);renderQuestionSummary(body,item);};const addError=MF.el("button","","🧩 Đưa vào Sổ lỗi");addError.onclick=()=>{MFStore.add("errors",{skill:"CE",type:"Đọc hiểu",source:item.title,context:q.text,original:item.questionResults[index]?.answer||"",corrected:q.answer,explanation:q.explanation,date:today(),reviewDate:today(),level:1,resolved:false,reviewCount:0});MF.toast("Đã thêm câu hỏi vào Sổ lỗi");};box.append(title,answerWrap,check,addError,feedback);body.append(box);});renderQuestionSummary(body,item);return section;}
function renderQuestionSummary(root,item){root.querySelector(".question-summary")?.remove();const answered=item.questionResults.filter(Boolean),right=answered.filter(x=>x.correct).length,summary=MF.el("div","question-summary",`Kết quả: ${right}/${item.questions.length} • ${item.score}% • ${answered.filter(x=>!x.correct).length} câu cần xem lại`);root.append(summary);}

function renderArticle(item){article.replaceChildren();const heading=MF.el("div","article-heading"),meta=MF.el("div","article-meta");meta.append(MF.el("span","level-badge",item.level),MF.el("span","",`${item.estimatedMinutes} phút`),MF.el("span","",item.topic||"Không có chủ đề"),MF.el("span","",`${wordCount(item.content)} từ`),MF.el("span",item.completed?"state done-state":"state",item.completed?"✓ Đã đọc":"○ Chưa đọc"));const tools=MF.el("div","reading-tools");[["A−","Giảm cỡ chữ","smaller"],["A+","Tăng cỡ chữ","larger"],["◉","Chế độ tập trung","focus"],["🖍","Bật/tắt từ vựng","highlight"],["🔊","Phát âm bài đọc","speak"],["■","Dừng phát âm","stop"]].forEach(([label,title,action])=>{const b=MF.el("button","",label);b.title=title;b.setAttribute("aria-label",title);b.dataset.tool=action;tools.append(b);});heading.append(MF.el("h2","",item.title),meta,tools);const text=highlightedText(item.content);text.style.fontSize=`${fontSize}px`;const questions=renderQuestions(item),nav=MF.el("div","reading-bottom-nav"),index=readings.indexOf(item);const prev=MF.el("button","","← Bài trước"),done=MF.el("button","primary",item.completed?"✓ Đã hoàn thành":"✓ Hoàn thành bài đọc"),next=MF.el("button","","Bài tiếp theo →");prev.disabled=index===0;next.disabled=index===readings.length-1;prev.onclick=()=>showReading(readings[index-1].id);next.onclick=()=>showReading(readings[index+1].id);done.onclick=()=>{item.completed=true;item.done=true;item.completedAt=item.completedAt||new Date().toISOString();item.progress=100;stopTimer();save();updateTimer();done.textContent="✓ Đã hoàn thành";MF.toast("Đã lưu tiến độ đọc hiểu");};nav.append(prev,done,next);article.append(heading,text,questions,nav);tools.onclick=event=>{const action=event.target.closest("button")?.dataset.tool;if(!action)return;if(action==="smaller")fontSize=Math.max(15,fontSize-1);if(action==="larger")fontSize=Math.min(26,fontSize+1);if(action==="focus")document.body.classList.toggle("reading-focus");if(action==="highlight")highlightOn=!highlightOn;if(action==="speak")MF.speak(item.content);if(action==="stop")speechSynthesis?.cancel();if(["smaller","larger","highlight"].includes(action))renderArticle(item);};}

function showReading(id){stopTimer();const item=readings.find(x=>x.id===id);if(!item)return;openReading=id;item.lastOpenedAt=new Date().toISOString();library.hidden=true;workspace.hidden=false;$("#mobileNotesButton").hidden=false;$("#readingBreadcrumb").textContent=`Đọc › ${item.topic||"Chủ đề"} › ${item.title}`;$("#workspaceLevel").textContent=item.level;$("#estimatedTime").textContent=`/ ${fmt(item.estimatedMinutes*60)}`;renderArticle(item);renderNotes(item);updateTimer();save(false);workspace.scrollIntoView({behavior:"smooth"});}
function renderNotes(item){$("#noteEditor").innerHTML=item.notes||"";$("#readingSummary").value=item.summary||"";$("#importantNote").textContent=item.importantNote?"★ Quan trọng":"☆ Đánh dấu quan trọng";countSummary();renderSavedVocabulary();renderStructures();renderTags();}
function saveNotes(){const item=current();if(!item)return;item.notes=$("#noteEditor").innerHTML;item.summary=$("#readingSummary").value;$("#noteSaveState").textContent="Đã lưu";save(false);}
let noteDebounce;function scheduleNotes(){$("#noteSaveState").textContent="Đang lưu…";clearTimeout(noteDebounce);noteDebounce=setTimeout(saveNotes,500);}
function renderSavedVocabulary(){const root=$("#savedVocabulary"),item=current();if(!root||!item)return;root.replaceChildren();if(!item.savedVocabulary.length)root.append(MF.el("p","empty-state","Bấm vào từ được tô sáng để thêm vào đây."));item.savedVocabulary.forEach((word,index)=>{const row=MF.el("article","saved-learning-item");row.append(MF.el("div","",`${word.word} — ${word.meaning||""}`));const speak=MF.el("button","","🔊"),open=MF.el("a","","Flashcard ↗"),remove=MF.el("button","","×");speak.setAttribute("aria-label",`Phát âm ${word.word}`);speak.onclick=()=>MF.speak(word.word);open.href=`vocabulary.html#${encodeURIComponent(word.word)}`;remove.setAttribute("aria-label",`Xóa ${word.word}`);remove.onclick=()=>{item.savedVocabulary.splice(index,1);save(false);renderSavedVocabulary();};row.append(speak,open,remove);root.append(row);});}
function renderStructures(){const root=$("#savedStructures"),item=current();if(!item)return;root.replaceChildren();if(!item.savedStructures.length)root.append(MF.el("p","empty-state","Chưa có cấu trúc được lưu."));item.savedStructures.forEach((value,index)=>{const row=MF.el("article","saved-learning-item");row.append(MF.el("div","",`${value.text} — ${value.meaning||""}\n${value.example||""}`));const edit=MF.el("button","","Sửa"),remove=MF.el("button","","×");edit.onclick=()=>{const text=prompt("Cấu trúc",value.text);if(text!==null){value.text=text;value.meaning=prompt("Ý nghĩa",value.meaning)||"";value.example=prompt("Ví dụ",value.example)||"";save(false);renderStructures();}};remove.onclick=()=>{item.savedStructures.splice(index,1);save(false);renderStructures();};row.append(edit,remove);root.append(row);});}
function renderTags(){const root=$("#readingTags"),item=current();root.replaceChildren();item.tags.forEach((tag,index)=>{const button=MF.el("button",`tag tag-${index%5}`,`${tag} ×`);button.onclick=()=>{item.tags.splice(index,1);save(false);renderTags();};root.append(button);});}
function countSummary(){const count=wordCount($("#readingSummary").value);$("#summaryCount").textContent=`${count} từ${count&& (count<50||count>80)?" • nên giữ 50–80 từ":""}`;}

function openForm(item=null){$("#readingId").value=item?.id||"";$("#readingTitle").value=item?.title||"";$("#readingTopic").value=item?.topic||"";$("#readingLevel").value=item?.level||"B1";$("#readingDate").value=item?.date||"";$("#readingMinutes").value=item?.estimatedMinutes||6;$("#readingContent").value=item?.content||"";$("#readingSource").value=item?.source||"";$("#readingLink").value=item?.link||"";$("#readingQuestions").value=(item?.questions||[]).map(q=>typeof q==="object"?`${q.text}|${q.type||"short"}|${(q.options||[]).join(";")}`:q).join("\n");$("#readingAnswers").value=(item?.answers||[]).join("\n");$("#readingExplanations").value=(item?.explanations||[]).join("\n");$("#readingTagInput").value=(item?.tags||[]).join(", ");$("#readingInitialNotes").value=(item?.notes||"").replace(/<[^>]+>/g,"");dialog.showModal();}
const lines=id=>$(id).value.split("\n").map(x=>x.trim()).filter(Boolean);

$("#readingForm").onsubmit=event=>{event.preventDefault();const id=$("#readingId").value||MF.uid("reading"),old=readings.find(x=>x.id===id)||{};const item=normalizeReading({...old,id,title:$("#readingTitle").value.trim(),content:$("#readingContent").value.trim(),topic:$("#readingTopic").value.trim(),level:$("#readingLevel").value,date:$("#readingDate").value,estimatedMinutes:Number($("#readingMinutes").value)||6,source:$("#readingSource").value.trim(),link:MF.validUrl($("#readingLink").value),questions:lines("#readingQuestions"),answers:lines("#readingAnswers"),explanations:lines("#readingExplanations"),tags:$("#readingTagInput").value.split(",").map(x=>x.trim()).filter(Boolean),notes:old.notes||$("#readingInitialNotes").value.trim()});if(!item.title||!item.content)return MF.toast("Hãy nhập tên và nội dung bài đọc");const index=readings.findIndex(x=>x.id===id);if(index>=0)readings[index]=item;else readings.push(item);save();dialog.close();MF.toast("Đã lưu bài đọc");};
cards.onclick=event=>{const b=event.target.closest("button[data-action]");if(!b)return;const item=readings.find(x=>x.id===b.dataset.id);if(b.dataset.action==="open")showReading(item.id);if(b.dataset.action==="edit")openForm(item);if(b.dataset.action==="copy"){const copy=normalizeReading({...clone(item),id:MF.uid("reading"),title:`${item.title} — bản sao`,completed:false,done:false,completedAt:""});readings.push(copy);save();MF.toast("Đã sao chép bài đọc");}if(b.dataset.action==="delete"&&confirm(`Xóa “${item.title}”?`)){readings=readings.filter(x=>x.id!==item.id);save();}};
$("#addReading").onclick=()=>openForm();$("[data-close]").onclick=()=>dialog.close();$("#backToLibrary").onclick=()=>{stopTimer();workspace.hidden=true;library.hidden=false;$("#mobileNotesButton").hidden=true;document.body.classList.remove("reading-focus","notes-open");};$("#timerToggle").onclick=toggleTimer;$("#timerReset").onclick=()=>{if(current()&&confirm("Đặt lại thời gian đọc của bài này?")){current().readingSeconds=0;updateTimer();save(false);}};
document.querySelectorAll("[data-note-tab]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-note-tab]").forEach(x=>x.classList.toggle("active",x===button));[["notes",$("#notesTab")],["vocabulary",$("#vocabularyTab")],["structures",$("#structuresTab")]].forEach(([name,panel])=>panel.hidden=name!==button.dataset.noteTab);});
document.querySelectorAll("[data-command]").forEach(button=>button.onclick=()=>{document.execCommand(button.dataset.command,false,button.dataset.value||null);$("#noteEditor").focus();scheduleNotes();});$("#noteEditor").addEventListener("input",scheduleNotes);$("#saveNote").onclick=saveNotes;$("#importantNote").onclick=()=>{const item=current();item.importantNote=!item.importantNote;saveNotes();$("#importantNote").textContent=item.importantNote?"★ Quan trọng":"☆ Đánh dấu quan trọng";};
$("#exportNote").onclick=()=>{const item=current(),text=`# ${item.title}\n\n## Ghi chú\n${$("#noteEditor").innerText}\n\n## Ý chính\n${item.summary||""}`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/markdown"}));a.download=`ghi-chu-${item.title.replace(/\W+/g,"-")}.md`;a.click();URL.revokeObjectURL(a.href);};
$("#readingSummary").addEventListener("input",()=>{countSummary();scheduleNotes();});$("#summaryGuide").onclick=()=>alert("Gợi ý tóm tắt:\n1. Xác định chủ đề chính.\n2. Tìm luận điểm của từng đoạn.\n3. Loại bỏ ví dụ phụ.\n4. Viết lại bằng từ của bạn.\n5. Giữ trong khoảng 50–80 từ.");
$("#structureForm").onsubmit=event=>{event.preventDefault();current().savedStructures.push({id:MF.uid("structure"),text:$("#structureText").value.trim(),meaning:$("#structureMeaning").value.trim(),example:$("#structureExample").value.trim()});event.target.reset();save(false);renderStructures();};$("#tagForm").onsubmit=event=>{event.preventDefault();const tag=$("#tagInput").value.trim();if(tag&&!current().tags.includes(tag))current().tags.push(tag);event.target.reset();save(false);renderTags();};
$("#mobileNotesButton").onclick=()=>document.body.classList.toggle("notes-open");document.addEventListener("keydown",event=>{if(event.key==="Escape"){popup.hidden=true;document.body.classList.remove("notes-open","reading-focus");if(dialog.open)dialog.close();}});window.addEventListener("beforeunload",()=>{stopTimer();if(openReading)saveNotes();});
async function loadVocab(){try{const fetched=await MF.fetchVocabulary(),central=MFStore.list("vocabulary");const map=new Map([...central,...fetched].map(item=>[String(item.word).toLocaleLowerCase("fr"),item]));vocabulary=[...map.values()];if(openReading)renderArticle(current());}catch(_){vocabulary=MFStore.list("vocabulary");MF.toast("Đang dùng kho từ đã lưu vì chưa tải được Google Sheets T6");}}
renderCards();loadVocab();
