const STORAGE="mon-francais-github-v1";
const defaults={seconds:0,sheetUrl:"",words:[
{id:1,word:"l’évolution",type:"nom féminin",meaning:"sự tiến bộ, sự phát triển",example:"L’évolution des technologies transforme notre quotidien.",tone:"violet",learned:false},
{id:2,word:"transformer",type:"verbe",meaning:"biến đổi, thay đổi",example:"L’intelligence artificielle transforme le monde du travail.",tone:"orange",learned:false},
{id:3,word:"la perspective",type:"nom féminin",meaning:"triển vọng, góc nhìn",example:"Cette expérience m’offre de nouvelles perspectives.",tone:"blue",learned:true},
{id:4,word:"la transformation numérique",type:"groupe nominal",meaning:"chuyển đổi số",example:"La transformation numérique est un phénomène mondial.",tone:"green",learned:false}],tasks:[{id:1,label:"Học 20 từ vựng mới",done:true},{id:2,label:"Làm bài tập ngữ pháp Subjonctif",done:true},{id:3,label:"Nghe podcast tiếng Pháp 15 phút",done:true},{id:4,label:"Viết một đoạn văn ngắn 100 từ",done:false},{id:5,label:"Luyện nói mô tả ngày của bạn 5 phút",done:false}]};
let state=JSON.parse(localStorage.getItem(STORAGE)||"null")||structuredClone(defaults),tick=null,selected="";
const $=s=>document.querySelector(s),save=()=>localStorage.setItem(STORAGE,JSON.stringify(state));
function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function format(n){return [Math.floor(n/3600),Math.floor(n%3600/60),n%60].map(x=>String(x).padStart(2,"0")).join(":")}
function renderTimer(){const percent=Math.min(100,Math.round(state.seconds/7200*100));$("#timer").textContent=format(state.seconds);$("#studyPercent").textContent=percent+"%";$("#studyBar").style.width=percent+"%"}
function renderWords(){$("#wordGrid").innerHTML=state.words.slice(-4).map(w=>`<article class="word ${w.tone}"><button class="audio" data-speak="${w.id}" aria-label="Phát âm">🔊</button><h3>${w.word}</h3><b>(${w.type}) ${w.meaning}</b><hr><p><i>Exemple:</i> ${w.example}</p><button class="learned ${w.learned?'yes':''}" data-learn="${w.id}">${w.learned?'✓':'i'}</button></article>`).join("");$("#wordCount").textContent=`${state.words.filter(w=>w.learned).length}/${state.words.length} từ đã thuộc`}
function renderTasks(){const done=state.tasks.filter(t=>t.done).length;$("#taskCount").textContent=`${done} / ${state.tasks.length} đã hoàn thành`;$("#taskBar").style.width=(done/state.tasks.length*100)+"%";$("#taskList").innerHTML=state.tasks.map(t=>`<label><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span class="${t.done?'done':''}">${t.label}</span></label>`).join("")}
function speak(w){if(!speechSynthesis)return toast("Trình duyệt chưa hỗ trợ phát âm");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${w.word}. ${w.example}`);u.lang="fr-FR";u.rate=.88;speechSynthesis.speak(u)}
const grammar=[['Subjonctif','Cách dùng và các thì',8,12],['COD / COI / Y / EN','Đại từ bổ ngữ trong câu',6,10],['Discours rapporté','Lời nói gián tiếp',5,10]];
const skills=[['CO','Nghe',72,'9 / 12 bài'],['CE','Đọc',65,'8 / 12 bài'],['PE','Viết',50,'6 / 12 bài'],['PO','Nói',42,'5 / 12 bài']];
function init(){const n=new Date(),h=n.getHours();$("#greeting").textContent=h<12?'Bonjour':h<18?'Bon après-midi':'Bonsoir';$("#today").textContent=new Intl.DateTimeFormat('vi-VN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(n);const days=Math.max(0,Math.ceil((new Date('2026-11-15')-n)/86400000)),percent=Math.min(100,Math.max(0,Math.round((1-days/60)*100)));$("#days").textContent=days;$("#examPercent").textContent=percent+'%';$("#ring").style.background=`conic-gradient(#33bb70 ${percent*3.6}deg,#e8edf4 0)`;$("#sheetUrl").value=state.sheetUrl||"";$("#grammarGrid").innerHTML=grammar.map(g=>`<article class="grammar"><div class="symbol">▤</div><div class="copy"><h3>${g[0]}</h3><p>${g[1]}</p><div class="mini"><span style="width:${g[2]/g[3]*100}%"></span></div></div><button data-quiz> Luyện tập ›</button></article>`).join('');$("#skills").innerHTML=skills.map(s=>`<div class="skill"><div class="row"><b>${s[0]}</b><span>— ${s[1]}</span><strong>${s[2]}%</strong></div><div class="mini"><span style="width:${s[2]}%"></span></div><small>${s[3]}</small></div>`).join('');renderTimer();renderWords();renderTasks()}
$("#startBtn").onclick=()=>{if(tick)return;tick=setInterval(()=>{state.seconds++;renderTimer();save()},1000);toast("Đã bắt đầu tính thời gian")};
$("#pauseBtn").onclick=()=>{clearInterval(tick);tick=null;save();toast("Đã tạm dừng")};
$("#resetBtn").onclick=()=>{if(confirm("Đặt lại thời gian học hôm nay?")){clearInterval(tick);tick=null;state.seconds=0;save();renderTimer()}};
$("#sheetUrl").onchange=e=>{state.sheetUrl=e.target.value.trim();save();toast("Đã lưu liên kết")};$("#sheetBtn").onclick=()=>state.sheetUrl?window.open(state.sheetUrl,'_blank','noopener'):toast("Hãy dán liên kết Google Sheets");
$("#openWordModal").onclick=()=>$("#wordModal").showModal();$("#saveWord").onclick=()=>{const word=$("#newWord").value.trim(),meaning=$("#newMeaning").value.trim(),example=$("#newExample").value.trim();if(!word||!meaning)return toast("Hãy nhập từ và nghĩa");state.words.push({id:Date.now(),word,type:'từ mới',meaning,example:example||'Ajoutez votre propre exemple.',tone:['violet','orange','blue','green'][state.words.length%4],learned:false});save();renderWords();$("#wordModal").close();toast("Đã thêm từ mới")};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)$("#"+b.dataset.close).close();if(b.dataset.speak)speak(state.words.find(w=>w.id==b.dataset.speak));if(b.dataset.learn){const w=state.words.find(w=>w.id==b.dataset.learn);w.learned=!w.learned;save();renderWords()}if(b.hasAttribute('data-quiz')){$("#quizModal").showModal();selected='';$("#quizResult").textContent='';document.querySelectorAll('.answers button').forEach(x=>x.classList.remove('selected'))}});
document.addEventListener('change',e=>{if(e.target.dataset.task){const t=state.tasks.find(x=>x.id==e.target.dataset.task);t.done=e.target.checked;save();renderTasks()}});document.querySelectorAll('.answers button').forEach(b=>b.onclick=()=>{selected=b.textContent;document.querySelectorAll('.answers button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$("#checkAnswer").onclick=()=>{const ok=selected==='fasses';$("#quizResult").textContent=ok?'Chính xác !':'Đáp án đúng là « fasses ».';$("#quizResult").className=ok?'correct':'wrong'};$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle('open');init();
