const STORAGE="mon-francais-github-v3",SHEET_ID="1YFaJsXJTqSx6uHM-JiE21w3QQ0O2eGNzHn74Jk4L0ME",DEFAULT_SHEET_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit`;
const defaults={seconds:0,timerMode:"up",countdownTotal:1500,countdownLeft:1500,sheetUrl:DEFAULT_SHEET_URL,words:[],allWords:[],mastery:{},tasks:[{id:1,label:"Học 20 từ vựng mới",done:false},{id:2,label:"Làm bài tập ngữ pháp Subjonctif",done:false},{id:3,label:"Nghe podcast tiếng Pháp 15 phút",done:false},{id:4,label:"Viết một đoạn văn ngắn 100 từ",done:false},{id:5,label:"Luyện nói mô tả ngày của bạn 5 phút",done:false}]};
const storedState=JSON.parse(localStorage.getItem(STORAGE)||localStorage.getItem("mon-francais-github-v2")||"null");
let state={...structuredClone(defaults),...(storedState||{}),mastery:storedState?.mastery||{}},tick=null,flashSession=[],flashIndex=0,flashRevealed=false;const $=selector=>document.querySelector(selector),save=()=>localStorage.setItem(STORAGE,JSON.stringify(state));
function toast(text){const node=$("#toast");node.textContent=text;node.classList.add("show");clearTimeout(node._timer);node._timer=setTimeout(()=>node.classList.remove("show"),2500);}
function format(seconds){return[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(v=>String(v).padStart(2,"0")).join(":");}
function renderTimer(){const down=state.timerMode==="down",shown=down?state.countdownLeft:state.seconds,percent=down?Math.max(0,Math.min(100,Math.round((1-state.countdownLeft/Math.max(1,state.countdownTotal))*100))):Math.min(100,Math.round(state.seconds/7200*100));$("#timer").textContent=format(shown);$("#studyPercent").textContent=`${percent}%`;$("#studyBar").style.width=`${percent}%`;$("#timerLauncher").style.setProperty("--timer-progress",`${percent*3.6}deg`);$("#countUpMode").classList.toggle("selected",!down);$("#countDownMode").classList.toggle("selected",down);$("#countdownSetting").hidden=!down;}
function stopTimer(){clearInterval(tick);tick=null;save();}
function startTimer(){if(tick)return;if(state.timerMode==="down"&&state.countdownLeft<=0)state.countdownLeft=state.countdownTotal;tick=setInterval(()=>{if(state.timerMode==="up")state.seconds++;else{state.countdownLeft=Math.max(0,state.countdownLeft-1);if(!state.countdownLeft){stopTimer();toast("Hết thời gian học. Bravo !");}}renderTimer();save();},1000);toast(state.timerMode==="up"?"Đã bắt đầu tính thời gian":"Đã bắt đầu đếm ngược");}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);}
function wordKey(word){return `${word.word}|${word.date||""}`.toLocaleLowerCase("fr");}
function masteryLabel(level){return["Chưa đánh giá","Chưa nhớ","Hơi nhớ","Đang thuộc","Gần thuộc","Đã thuộc"][level||0];}
function renderWords(message=""){const grid=$("#wordGrid");if(!state.words.length)grid.innerHTML=`<div class="empty-state">${escapeHtml(message||"Chưa có từ vựng cho ngày được chọn.")}</div>`;else grid.innerHTML=state.words.map((word,index)=>{const level=state.mastery[wordKey(word)]||0;return`<article class="word ${["violet","orange","blue","green"][index%4]}"><button class="audio" data-speak="${word.id}" aria-label="Phát âm">🔊</button><h3>${escapeHtml(word.word)}</h3><b>${escapeHtml(word.meaning)}</b><hr><p><i>Exemple:</i> ${escapeHtml(word.example||"Chưa có ví dụ")}</p><span class="mastery-tag level-${level}">${level}/5 • ${masteryLabel(level)}</span></article>`;}).join("");const mastered=state.words.filter(word=>(state.mastery[wordKey(word)]||0)===5).length;$("#wordCount").textContent=`${mastered}/${state.words.length} từ ở mức 5`;} 
function gvizDateToIso(value){if(!value)return"";const match=String(value).match(/^Date\((\d+),(\d+),(\d+)\)$/);if(match)return`${match[1]}-${String(Number(match[2])+1).padStart(2,"0")}-${match[3].padStart(2,"0")}`;const date=new Date(value);if(Number.isNaN(date.getTime()))return"";return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
async function fetchAllWords(){const endpoint=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=T6&headers=1&t=${Date.now()}`,response=await fetch(endpoint);if(!response.ok)throw new Error("sheet");const raw=await response.text(),start=raw.indexOf("{"),end=raw.lastIndexOf("}");if(start<0||end<0)throw new Error("format");const data=JSON.parse(raw.slice(start,end+1));return(data.table.rows||[]).map((row,index)=>{const c=row.c||[];return{id:`sheet-${index}`,word:String(c[1]?.v??"").trim(),meaning:String(c[3]?.v??"").trim(),example:String(c[4]?.v??"").trim(),date:gvizDateToIso(c[9]?.v)};}).filter(item=>item.word&&item.date);}
function formatDate(iso){const [y,m,d]=iso.split("-");return`${d}/${m}/${y}`;}
async function loadVocabularyIndex(){const select=$("#vocabDate");select.disabled=true;try{state.allWords=await fetchAllWords();const dates=[...new Set(state.allWords.map(word=>word.date))].sort((a,b)=>b.localeCompare(a));select.replaceChildren();dates.forEach(date=>{const option=document.createElement("option");option.value=date;option.textContent=formatDate(date);select.append(option);});if(dates.length){select.value=dates[0];showSelectedDate();}else{renderWords("Trang T6 chưa có dòng nào có ngày ở cột J.");$("#wordCount").textContent="Chưa có ngày học";}save();}catch(_){select.replaceChildren();renderWords("Không thể tải trang T6. Hãy đặt quyền: Bất kỳ ai có liên kết đều có thể xem.");$("#wordCount").textContent="Không thể tải danh sách ngày";toast("Không thể đọc Google Sheets");}finally{select.disabled=false;}}
function showSelectedDate(){const date=$("#vocabDate").value;if(!date)return toast("Chưa có ngày học trong trang T6");state.words=state.allWords.filter(word=>word.date===date).map((word,index)=>({...word,id:`${date}-${index}`}));save();renderWords();}
function speak(word){if(!("speechSynthesis"in window))return toast("Trình duyệt chưa hỗ trợ phát âm");speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`${word.word}. ${word.example||""}`);utterance.lang="fr-FR";utterance.rate=.88;speechSynthesis.speak(utterance);}
function startFlashcards(){if(!state.allWords.length)return toast("Chưa tải được từ vựng từ T6");const ranked=[...state.allWords].sort((a,b)=>{const diff=(state.mastery[wordKey(a)]||0)-(state.mastery[wordKey(b)]||0);return diff||Math.random()-.5;});flashSession=ranked.slice(0,20);flashIndex=0;flashRevealed=false;renderFlashcard();$("#flashcardDialog").showModal();}
function renderFlashcard(){if(!flashSession.length)return;const word=flashSession[flashIndex];$("#flashProgress").textContent=`${flashIndex+1} / ${flashSession.length}`;$("#flashWord").textContent=word.word;$("#flashMeaning").textContent=word.meaning||"Chưa có nghĩa";$("#flashExample").textContent=word.example||"Chưa có ví dụ";$("#flashAnswer").hidden=!flashRevealed;$("#flashCard").classList.toggle("revealed",flashRevealed);document.querySelectorAll("#masteryButtons button").forEach(button=>button.classList.toggle("selected",Number(button.dataset.level)===(state.mastery[wordKey(word)]||0)));}
function nextFlash(){if(flashIndex<flashSession.length-1){flashIndex++;flashRevealed=false;renderFlashcard();}else{toast("Bạn đã hoàn thành 20 flashcard");$("#flashcardDialog").close();renderWords();}}
function showAllWords(){const list=$("#allWordsList"),sorted=[...state.allWords].sort((a,b)=>a.word.localeCompare(b.word,"fr",{sensitivity:"base"}));list.replaceChildren();sorted.forEach((word,index)=>{const row=document.createElement("article");row.className="all-word-row";const number=document.createElement("span");number.textContent=String(index+1).padStart(3,"0");const copy=document.createElement("div");const title=document.createElement("h3");title.textContent=word.word;const meaning=document.createElement("p");meaning.textContent=word.meaning||"Chưa có nghĩa";const meta=document.createElement("small");const level=state.mastery[wordKey(word)]||0;meta.textContent=`${word.date?formatDate(word.date):""} • Mức ${level}/5 – ${masteryLabel(level)}`;copy.append(title,meaning,meta);const audio=document.createElement("button");audio.textContent="🔊";audio.setAttribute("aria-label",`Phát âm ${word.word}`);audio.onclick=()=>speak(word);row.append(number,copy,audio);list.append(row);});$("#allWordsCount").textContent=`${sorted.length} từ`;$("#allWordsDialog").showModal();}
function renderTasks(){const done=state.tasks.filter(task=>task.done).length;$("#taskCount").textContent=`${done} / ${state.tasks.length} đã hoàn thành`;$("#taskBar").style.width=`${state.tasks.length?done/state.tasks.length*100:0}%`;$("#taskList").innerHTML=state.tasks.map(task=>`<label><input type="checkbox" data-task="${task.id}" ${task.done?"checked":""}><span class="${task.done?"done":""}">${escapeHtml(task.label)}</span></label>`).join("");}
function init(){const now=new Date(),hour=now.getHours();$("#greeting").textContent=hour<12?"Bonjour":hour<18?"Bon après-midi":"Bonsoir";$("#today").textContent=new Intl.DateTimeFormat("vi-VN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now);$("#sheetUrl").value=state.sheetUrl||DEFAULT_SHEET_URL;$("#countdownMinutes").value=Math.round(state.countdownTotal/60);renderTimer();renderWords("Đang tải danh sách ngày có từ vựng…");renderTasks();loadVocabularyIndex();}
$("#startBtn").onclick=startTimer;$("#pauseBtn").onclick=()=>{stopTimer();toast("Đã tạm dừng");};$("#resetBtn").onclick=()=>{if(!confirm("Đặt lại đồng hồ hiện tại?"))return;stopTimer();if(state.timerMode==="up")state.seconds=0;else state.countdownLeft=state.countdownTotal;save();renderTimer();};$("#countUpMode").onclick=()=>{stopTimer();state.timerMode="up";save();renderTimer();};$("#countDownMode").onclick=()=>{stopTimer();state.timerMode="down";save();renderTimer();};$("#applyCountdown").onclick=()=>{const minutes=Math.round(Number($("#countdownMinutes").value));if(!Number.isFinite(minutes)||minutes<1||minutes>480)return toast("Nhập từ 1 đến 480 phút");stopTimer();state.countdownTotal=minutes*60;state.countdownLeft=state.countdownTotal;save();renderTimer();toast(`Đã đặt đếm ngược ${minutes} phút`);};
$("#loadWords").onclick=showSelectedDate;$("#vocabDate").onchange=showSelectedDate;$("#flashcardBtn").onclick=startFlashcards;$("#allWordsBtn").onclick=showAllWords;$("#flashCard").onclick=()=>{flashRevealed=!flashRevealed;renderFlashcard();};$("#flashNext").onclick=nextFlash;$("#flashSpeak").onclick=()=>flashSession[flashIndex]&&speak(flashSession[flashIndex]);$("#masteryButtons").onclick=event=>{const button=event.target.closest("button[data-level]");if(!button||!flashSession.length)return;state.mastery[wordKey(flashSession[flashIndex])]=Number(button.dataset.level);save();renderFlashcard();setTimeout(nextFlash,180);};
$("#sheetUrl").onchange=event=>{state.sheetUrl=event.target.value.trim();save();toast("Đã lưu liên kết");};$("#sheetBtn").onclick=()=>window.open(state.sheetUrl||DEFAULT_SHEET_URL,"_blank","noopener");$("#timerLauncher").onclick=()=>{const popover=$("#timerPopover");popover.hidden=!popover.hidden;$("#timerLauncher").setAttribute("aria-expanded",String(!popover.hidden));};$("#timerClose").onclick=()=>{$("#timerPopover").hidden=true;$("#timerLauncher").setAttribute("aria-expanded","false");};
document.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.dataset.close){const target=$("#"+button.dataset.close);if(target?.open)target.close();}if(button.dataset.speak){const word=state.words.find(item=>item.id===button.dataset.speak);if(word)speak(word);}});document.addEventListener("change",event=>{if(!event.target.dataset.task)return;const task=state.tasks.find(item=>item.id==event.target.dataset.task);if(task)task.done=event.target.checked;save();renderTasks();});$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");init();
