const $=selector=>document.querySelector(selector),today=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toISOString();
const DAY=86400000,VOCAB_CACHE="mf-vocabulary-cache-v2",STATS_KEY="mf-vocabulary-stats-v1";
let words=MFStore.list("vocabulary").map(normalizeWord),session=null,currentIndex=0,answerVisible=false,lastReview=null,exerciseType="mcq",exerciseWord=null,matchState=[];
let stats=MF.read(STATS_KEY,{correct:0,wrong:0,currentStreak:0,bestStreak:0,activeDays:[]});
function normalizeWord(word){return{id:word.id||MF.uid("vocab"),word:String(word.word||"").trim(),pronunciation:word.pronunciation||"",partOfSpeech:word.partOfSpeech||word.type||"",meaning:word.meaning||"",example:word.example||"",exampleTranslation:word.exampleTranslation||"",topic:word.topic||"",level:word.level||"B1",date:word.date||"",source:word.source||"sheet",mastery:Number(word.mastery)||0,difficult:Boolean(word.difficult),favorite:Boolean(word.favorite),notes:word.notes||"",correctCount:Number(word.correctCount)||0,wrongCount:Number(word.wrongCount)||0,streak:Number(word.streak)||0,lastReviewedAt:word.lastReviewedAt||"",nextReviewAt:word.nextReviewAt||"",reviewInterval:Number(word.reviewInterval)||0,createdAt:word.createdAt||now(),updatedAt:word.updatedAt||now()};}
function key(word){return `${word.word}|${word.date||""}`.toLocaleLowerCase("fr");}
function saveWords(){MFStore.set("vocabulary",words);MF.write(VOCAB_CACHE,words);renderAll();}
function saveStats(){if(!stats.activeDays.includes(today()))stats.activeDays.push(today());stats.activeDays=stats.activeDays.slice(-90);MF.write(STATS_KEY,stats);}
function addDays(days){return new Date(Date.now()+days*DAY).toISOString().slice(0,10);}
function due(word){return word.mastery>0&&(!word.nextReviewAt||word.nextReviewAt<=today());}
function filteredWords(){const search=$("#vocabSearch").value.trim().toLocaleLowerCase("fr"),date=$("#vocabDate").value;return words.filter(item=>(!date||item.date===date)&&(!search||[item.word,item.meaning,item.example,item.topic].some(value=>String(value).toLocaleLowerCase("fr").includes(search))));}
function mergeWords(fetched){const map=new Map(words.map(item=>[key(item),item]));fetched.forEach(raw=>{const incoming=normalizeWord({...raw,source:"sheet"}),existing=map.get(key(incoming));if(existing)Object.assign(existing,{word:incoming.word,meaning:incoming.meaning||existing.meaning,example:incoming.example||existing.example,date:incoming.date||existing.date,partOfSpeech:incoming.partOfSpeech||existing.partOfSpeech,updatedAt:now()});else map.set(key(incoming),incoming);});words=[...map.values()];saveWords();}
async function syncSheet(){const status=$("#sheetStatus");status.textContent="Đang đồng bộ Google Sheets T6…";try{const fetched=await MF.fetchVocabulary();mergeWords(fetched);status.textContent=`Đã đồng bộ ${fetched.length} dòng từ T6 • ${new Date().toLocaleTimeString("vi-VN")}`;MF.toast("Đồng bộ từ vựng thành công");}catch(_){const cached=MF.read(VOCAB_CACHE,[]);if(!words.length&&cached.length)words=cached.map(normalizeWord);status.textContent="Không tải được T6 — đang dùng dữ liệu gần nhất trên thiết bị.";renderAll();}}
function populateDates(){const select=$("#vocabDate"),value=select.value,dates=[...new Set(words.map(item=>item.date).filter(Boolean))].sort().reverse();select.replaceChildren(new Option("Tất cả ngày có từ",""));dates.forEach(date=>select.add(new Option(new Intl.DateTimeFormat("vi-VN").format(new Date(`${date}T12:00:00`)),date)));select.value=dates.includes(value)?value:"";}
function selectSessionWords(source=words){const unique=list=>[...new Map(list.map(item=>[item.id,item])).values()],dueWords=source.filter(due).sort((a,b)=>(a.nextReviewAt||"").localeCompare(b.nextReviewAt||"")).slice(0,10),hard=source.filter(item=>item.difficult||item.mastery<=2||item.wrongCount>item.correctCount).filter(item=>!dueWords.includes(item)).slice(0,5),fresh=source.filter(item=>item.mastery===0).filter(item=>!dueWords.includes(item)&&!hard.includes(item)).slice(0,5);let selected=unique([...dueWords,...hard,...fresh]);if(selected.length<20)selected=unique([...selected,...source.slice().sort((a,b)=>(a.nextReviewAt||"9999").localeCompare(b.nextReviewAt||"9999"))]).slice(0,20);return selected;}
function startSession(custom=null){const selected=custom||selectSessionWords(filteredWords());if(!selected.length)return MF.toast("Chưa có từ phù hợp để ôn");session={id:MF.uid("review"),startedAt:now(),completedAt:"",vocabularyIds:selected.map(item=>item.id),currentIndex:0,correctCount:0,wrongCount:0,answers:[],durationSeconds:0,completed:false};currentIndex=0;answerVisible=false;MFStore.add("reviewSessions",session);renderFlashcard();renderAll();}
function currentWord(){return session?words.find(item=>item.id===session.vocabularyIds[currentIndex]):null;}
function updateSession(){if(!session)return;session.currentIndex=currentIndex;const list=MFStore.list("reviewSessions"),index=list.findIndex(item=>item.id===session.id);if(index>=0){list[index]={...session};MFStore.set("reviewSessions",list);}}
function continueSession(){const active=MFStore.list("reviewSessions").reverse().find(item=>!item.completed);if(!active)return MF.toast("Không có phiên chưa hoàn thành");session=active;currentIndex=Math.min(active.currentIndex||0,active.vocabularyIds.length-1);answerVisible=false;renderFlashcard();renderAll();}
function renderPlan(){const dueCount=words.filter(due).length,hardCount=words.filter(item=>item.difficult||item.mastery>0&&item.mastery<=2).length,newCount=words.filter(item=>item.mastery===0).length,done=session?.answers?.length||0,total=session?.vocabularyIds?.length||20;$("#reviewProgress").textContent=`${done}/${total}`;$("#reviewRing").style.setProperty("--progress",`${Math.round(done/Math.max(1,total)*360)}deg`);$("#dueCount").textContent=dueCount;$("#hardCount").textContent=hardCount;$("#newCount").textContent=newCount;const chart=$("#masteryChart");chart.replaceChildren();for(let level=1;level<=5;level++){const count=words.filter(item=>item.mastery===level).length,percent=words.length?Math.round(count/words.length*100):0,row=MF.el("div",`mastery-row level-${level}`);row.append(MF.el("span","",`Cấp độ ${level}`));const bar=MF.el("i");bar.style.width=`${percent}%`;const track=MF.el("b");track.append(bar);row.append(track,MF.el("small","",`${count} • ${percent}%`));chart.append(row);}}
function renderFlashcard(){const word=currentWord();$("#flashcardEmpty").hidden=Boolean(word);$("#vocabFlashcard").hidden=!word;if(!word){$("#cardCounter").textContent="Chưa bắt đầu";return;}$("#cardCounter").textContent=`Thẻ ${currentIndex+1} / ${session.vocabularyIds.length}`;$("#flashWord").textContent=word.word;$("#flashPronunciation").textContent=word.pronunciation;$("#flashPart").textContent=word.partOfSpeech||"Từ vựng";$("#flashMeaning").textContent=word.meaning||"Chưa có nghĩa";$("#flashExample").textContent=word.example||"Chưa có câu ví dụ";$("#flashTranslation").textContent=word.exampleTranslation;$("#toggleFavorite").textContent=word.favorite?"★":"☆";$("#markDifficult").textContent=word.difficult?"⚑ Từ khó":"⚐ Đánh dấu từ khó";const tags=$("#flashTags");tags.replaceChildren();[word.topic,word.level].filter(Boolean).forEach((tag,index)=>tags.append(MF.el("span",`tag tag-${index}`,tag)));$("#flashAnswer").hidden=!answerVisible;$("#masteryButtons").hidden=!answerVisible;$("#revealAnswer").textContent=answerVisible?"Ẩn nghĩa":"Hiện nghĩa";$("#previousCard").disabled=currentIndex===0;$("#nextCard").disabled=currentIndex>=session.vocabularyIds.length-1;}
function review(level){const word=currentWord();if(!word||!answerVisible)return MF.toast("Hãy hiện nghĩa trước khi tự đánh giá");const previous={...word},days=[1,1,3,7,word.correctCount>=3?45:21][level-1];word.mastery=level;word.lastReviewedAt=now();word.nextReviewAt=addDays(days);word.reviewInterval=days;word.updatedAt=now();if(level<=2){word.wrongCount++;word.streak=0;session.wrongCount++;}else{word.correctCount++;word.streak++;session.correctCount++;}session.answers.push({vocabularyId:word.id,level,correct:level>=3,answeredAt:now()});lastReview={wordId:word.id,previous,index:currentIndex};$("#undoReview").disabled=false;saveWords();saveStats();if(currentIndex<session.vocabularyIds.length-1){currentIndex++;answerVisible=false;updateSession();renderFlashcard();}else finishSession();}
function undoReview(){if(!lastReview)return;const index=words.findIndex(item=>item.id===lastReview.wordId);if(index>=0)words[index]=lastReview.previous;session.answers.pop();currentIndex=lastReview.index;session.correctCount=session.answers.filter(x=>x.correct).length;session.wrongCount=session.answers.filter(x=>!x.correct).length;lastReview=null;$("#undoReview").disabled=true;answerVisible=true;saveWords();updateSession();renderFlashcard();}
function finishSession(){session.completed=true;session.completedAt=now();updateSession();const total=session.answers.length,wrong=session.answers.filter(x=>!x.correct),percent=total?Math.round(session.correctCount/total*100):0;$("#sessionSummary").innerHTML=`<div class="summary-metrics"><span><b>${total}</b>Từ đã ôn</span><span><b>${session.correctCount}</b>Nhớ tốt</span><span><b>${wrong.length}</b>Cần ôn lại</span><span><b>${percent}%</b>Độ chính xác</span></div><p><b>Từ cần ôn:</b> ${wrong.map(result=>words.find(w=>w.id===result.vocabularyId)?.word).filter(Boolean).join(", ")||"Không có"}</p>`;$("#sessionDialog").showModal();renderAll();}
function renderStats(){const answered=stats.correct+stats.wrong,accuracy=answered?Math.round(stats.correct/answered*100):0;$("#accuracyStat").textContent=`${accuracy}%`;$("#masteredStat").textContent=words.filter(item=>item.mastery>=4).length;$("#reviewStat").textContent=words.filter(due).length;$("#streakStat").textContent=stats.currentStreak;$("#studyStreak").textContent=calculateDayStreak();$("#mcqCount").textContent=`${Math.min(12,words.length)} câu`;$("#matchCount").textContent=`${Math.min(10,words.length)} cặp`;$("#writeCount").textContent=`${Math.min(8,words.length)} câu`;$("#contextCount").textContent=`${Math.min(6,words.filter(w=>w.example).length)} câu`;}
function calculateDayStreak(){const days=new Set(stats.activeDays),date=new Date();let result=0;for(;;){const iso=date.toISOString().slice(0,10);if(!days.has(iso))break;result++;date.setDate(date.getDate()-1);}return result;}
function renderAll(){populateDates();renderPlan();renderStats();renderArchive();}

function pool(){return filteredWords().filter(item=>item.word&&item.meaning);}
function randomWord(list=pool()){return list[Math.floor(Math.random()*list.length)];}
function normalizeAnswer(value){return String(value||"").trim().toLocaleLowerCase("fr").normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
function recordExercise(word,correct,type,answer,hints=0){if(correct){stats.correct++;stats.currentStreak++;stats.bestStreak=Math.max(stats.bestStreak,stats.currentStreak);word.correctCount++;}else{stats.wrong++;stats.currentStreak=0;word.wrongCount++;word.difficult=true;}saveStats();saveWords();const result={id:MF.uid("exercise"),type,vocabularyId:word.id,answer,correct,hintsUsed:hints,answeredAt:now()};const data=MFStore.snapshot(),history=Array.isArray(data.settings.exerciseResults)?data.settings.exerciseResults:[];MFStore.configure("settings",{exerciseResults:[...history,result].slice(-500)});renderStats();}
function feedback(root,word,correct){const box=MF.el("div",correct?"exercise-feedback correct":"exercise-feedback wrong");box.append(MF.el("b","",correct?"✓ Chính xác":"✗ Chưa đúng"),MF.el("p","",`${word.word} — ${word.meaning}`),MF.el("small","",word.example||""));if(!correct){const error=MF.el("button","","🧩 Đưa vào Sổ lỗi");error.onclick=()=>{MFStore.add("errors",{skill:"CE",type:"Từ vựng",source:"Bài tập từ vựng",context:word.example||word.word,original:"Trả lời sai",corrected:`${word.word} — ${word.meaning}`,explanation:"Ôn lại bằng flashcard và ngữ cảnh.",date:today(),reviewDate:today(),level:1,resolved:false,reviewCount:0});MF.toast("Đã thêm vào Sổ lỗi");};box.append(error);}root.append(box);}
function renderExercise(){const root=$("#exerciseArea");root.replaceChildren();const list=pool();if(!list.length)return root.append(MF.el("div","empty-state","Chưa đủ từ vựng để tạo bài tập."));exerciseWord=randomWord(list);if(exerciseType==="mcq")renderMcq(root,list);if(exerciseType==="fill")renderFill(root,list);if(exerciseType==="dictation")renderDictation(root,list);if(exerciseType==="match")renderMatch(root,list);}
function renderMcq(root,list){const word=exerciseWord,options=[word,...list.filter(x=>x.id!==word.id).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);root.append(MF.el("small","","CHỌN NGHĨA ĐÚNG"),MF.el("h3","",word.word));const choices=MF.el("div","choice-grid");options.forEach(option=>{const button=MF.el("button","",option.meaning);button.onclick=()=>{const correct=option.id===word.id;choices.querySelectorAll("button").forEach(b=>b.disabled=true);recordExercise(word,correct,"multiple-choice",option.meaning);feedback(root,word,correct);};choices.append(button);});root.append(choices);}
function renderFill(root){const word=exerciseWord,example=word.example||`Il faut utiliser le mot « ${word.word} » dans cette phrase.`,pattern=new RegExp(word.word.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"iu"),question=pattern.test(example)?example.replace(pattern,"________"):example;root.append(MF.el("small","","ĐIỀN TỪ VÀO NGỮ CẢNH"),MF.el("h3","",question));const input=document.createElement("input");input.placeholder="Nhập từ còn thiếu…";const buttons=MF.el("div","exercise-buttons"),check=MF.el("button","primary","Kiểm tra"),hint=MF.el("button","","Gợi ý");let hints=0;hint.onclick=()=>{hints++;hint.textContent=`Gợi ý: ${word.word.slice(0,Math.min(word.word.length,hints+1))}…`;};check.onclick=()=>{const correct=normalizeAnswer(input.value)===normalizeAnswer(word.word);input.disabled=check.disabled=hint.disabled=true;recordExercise(word,correct,"fill",input.value,hints);feedback(root,word,correct);};buttons.append(check,hint);root.append(input,buttons);}
function renderDictation(root){const word=exerciseWord;root.append(MF.el("small","","NGHE VÀ VIẾT"),MF.el("h3","","Nghe rồi nhập lại từ tiếng Pháp"));const audio=MF.el("button","dictation-play","🔊 Phát âm");audio.onclick=()=>MF.speak(word.word);const slow=MF.el("button","","🐢 Đọc chậm");slow.onclick=()=>{if(!("speechSynthesis" in window))return;const u=new SpeechSynthesisUtterance(word.word);u.lang="fr-FR";u.rate=.65;speechSynthesis.speak(u);};const input=document.createElement("input");input.placeholder="Nhập từ bạn nghe được…";const check=MF.el("button","primary","Kiểm tra");check.onclick=()=>{const correct=normalizeAnswer(input.value)===normalizeAnswer(word.word);input.disabled=check.disabled=true;recordExercise(word,correct,"dictation",input.value);feedback(root,word,correct);};root.append(audio,slow,input,check);}
function renderMatch(root,list){const selected=list.sort(()=>Math.random()-.5).slice(0,Math.min(6,list.length));matchState=[];root.append(MF.el("small","","GHÉP TỪ VỚI NGHĨA"));const board=MF.el("div","match-board"),left=MF.el("div"),right=MF.el("div");selected.forEach(word=>{const button=MF.el("button","",word.word);button.dataset.id=word.id;button.dataset.side="word";left.append(button);});selected.slice().sort(()=>Math.random()-.5).forEach(word=>{const button=MF.el("button","",word.meaning);button.dataset.id=word.id;button.dataset.side="meaning";right.append(button);});board.onclick=event=>{const button=event.target.closest("button");if(!button||button.disabled)return;board.querySelectorAll(`button[data-side="${button.dataset.side}"]`).forEach(x=>x.classList.remove("selected"));button.classList.add("selected");matchState=matchState.filter(x=>x.side!==button.dataset.side);matchState.push({side:button.dataset.side,id:button.dataset.id,button});if(matchState.length===2){const correct=matchState[0].id===matchState[1].id,word=words.find(x=>x.id===matchState[0].id);if(correct){matchState.forEach(x=>{x.button.disabled=true;x.button.classList.add("matched");});recordExercise(word,true,"match",word.meaning);}else{matchState.forEach(x=>x.button.classList.add("wrong"));setTimeout(()=>matchState.forEach(x=>x.button.classList.remove("wrong","selected")),500);recordExercise(word,false,"match","");}matchState=[];}};board.append(left,right);root.append(board);}

function renderArchive(){const root=$("#archiveList");if(!root)return;const search=$("#archiveSearch").value.trim().toLocaleLowerCase("fr"),mastery=$("#archiveMastery").value,difficult=$("#archiveDifficult").checked,dueOnly=$("#archiveDue").checked;const list=words.filter(item=>(!search||`${item.word} ${item.meaning} ${item.topic}`.toLocaleLowerCase("fr").includes(search))&&(mastery===""||item.mastery===Number(mastery))&&(!difficult||item.difficult)&&(!dueOnly||due(item))).sort((a,b)=>a.word.localeCompare(b.word,"fr"));$("#archiveCount").textContent=`${list.length} từ`;root.replaceChildren();list.forEach(word=>{const row=MF.el("article","archive-row");row.append(MF.el("div","",`${word.word}\n${word.meaning}`),MF.el("small","",`${word.partOfSpeech||"—"} • ${word.date||"Không ngày"}`),MF.el("span",`mastery-badge level-${word.mastery}`,`Mức ${word.mastery}`));const speak=MF.el("button","","🔊"),study=MF.el("button","primary","Ôn"),edit=MF.el("button","","Sửa");speak.onclick=()=>MF.speak(word.word);study.onclick=()=>{$("#archiveDialog").close();startSession([word]);};edit.onclick=()=>openWordForm(word);row.append(speak,study,edit);root.append(row);});}
function openWordForm(word=null){$("#wordId").value=word?.id||"";$("#wordText").value=word?.word||"";$("#wordPronunciation").value=word?.pronunciation||"";$("#wordPart").value=word?.partOfSpeech||"";$("#wordMeaning").value=word?.meaning||"";$("#wordExample").value=word?.example||"";$("#wordTranslation").value=word?.exampleTranslation||"";$("#wordTopic").value=word?.topic||"";$("#wordLevel").value=word?.level||"B1";$("#wordDate").value=word?.date||today();$("#wordNotes").value=word?.notes||"";$("#wordDialog").showModal();}

$("#syncSheet").onclick=syncSheet;$("#vocabSearch").oninput=()=>{renderAll();if(!session)renderExercise();};$("#vocabDate").onchange=()=>{if(!session)renderExercise();};$("#reviewToday").onclick=()=>startSession();$("#startSession").onclick=()=>startSession();$("#continueSession").onclick=continueSession;$("#previousCard").onclick=()=>{if(session&&currentIndex>0){currentIndex--;answerVisible=false;updateSession();renderFlashcard();}};$("#nextCard").onclick=()=>{if(session&&currentIndex<session.vocabularyIds.length-1){currentIndex++;answerVisible=false;updateSession();renderFlashcard();}};
$("#revealAnswer").onclick=()=>{answerVisible=!answerVisible;renderFlashcard();};$("#speakWord").onclick=()=>MF.speak(currentWord()?.word||"");$("#speakExample").onclick=()=>MF.speak(currentWord()?.example||"");$("#toggleFavorite").onclick=()=>{const word=currentWord();word.favorite=!word.favorite;saveWords();renderFlashcard();};$("#markDifficult").onclick=()=>{const word=currentWord();word.difficult=!word.difficult;saveWords();renderFlashcard();};$("#masteryButtons").onclick=event=>{const level=Number(event.target.closest("button")?.dataset.level);if(level)review(level);};$("#undoReview").onclick=undoReview;
$("#wordToError").onclick=()=>{const word=currentWord();if(!word)return;MFStore.add("errors",{skill:"CE",type:"Từ vựng",source:"Flashcard",context:word.example||word.word,original:word.word,corrected:word.meaning,explanation:"Ôn lại từ khó bằng Active Recall.",date:today(),reviewDate:today(),level:1,resolved:false,reviewCount:0});MF.toast("Đã thêm vào Sổ lỗi");};
$("#openWordNote").onclick=()=>{const word=currentWord();if(!word)return;$("#wordNoteText").value=word.notes||"";$("#noteDialog").showModal();};$("#wordNoteForm").onsubmit=event=>{event.preventDefault();currentWord().notes=$("#wordNoteText").value;saveWords();$("#noteDialog").close();MF.toast("Đã lưu ghi chú");};
document.querySelectorAll("[data-exercise]").forEach(button=>button.onclick=()=>{exerciseType=button.dataset.exercise;document.querySelectorAll("[data-exercise]").forEach(x=>x.classList.toggle("active",x===button));renderExercise();});document.querySelectorAll("[data-open-exercise]").forEach(button=>button.onclick=()=>{exerciseType=button.dataset.openExercise;document.querySelector(`[data-exercise="${exerciseType}"]`).click();});$("#newExercise").onclick=renderExercise;
$("#openArchive").onclick=()=>{$("#archiveDialog").showModal();renderArchive();};["#archiveSearch","#archiveMastery","#archiveDifficult","#archiveDue"].forEach(selector=>$(selector).addEventListener("input",renderArchive));$("#addWord").onclick=()=>openWordForm();
$("#wordForm").onsubmit=event=>{event.preventDefault();const id=$("#wordId").value,wordText=$("#wordText").value.trim(),existing=words.find(item=>item.id===id),duplicate=words.find(item=>item.id!==id&&item.word.toLocaleLowerCase("fr")===wordText.toLocaleLowerCase("fr"));if(duplicate)return MF.toast("Từ này đã có trong kho");const value=normalizeWord({...existing,id:id||MF.uid("manual"),word:wordText,pronunciation:$("#wordPronunciation").value.trim(),partOfSpeech:$("#wordPart").value.trim(),meaning:$("#wordMeaning").value.trim(),example:$("#wordExample").value.trim(),exampleTranslation:$("#wordTranslation").value.trim(),topic:$("#wordTopic").value.trim(),level:$("#wordLevel").value,date:$("#wordDate").value,notes:$("#wordNotes").value.trim(),source:existing?.source||"manual",updatedAt:now()});if(existing)words[words.findIndex(item=>item.id===id)]=value;else words.push(value);saveWords();$("#wordDialog").close();MF.toast("Đã lưu từ vựng");};
document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>$("#"+button.dataset.close).close());$("#reviewMistakes").onclick=()=>{const selected=session.answers.filter(x=>!x.correct).map(x=>words.find(w=>w.id===x.vocabularyId)).filter(Boolean);$("#sessionDialog").close();startSession(selected);};$("#practiceAfterSession").onclick=()=>{$("#sessionDialog").close();renderExercise();document.querySelector(".quick-exercises").scrollIntoView({behavior:"smooth"});};
document.addEventListener("keydown",event=>{if(["1","2","3","4","5"].includes(event.key)&&answerVisible&&!document.activeElement.matches("input,textarea,[contenteditable]"))review(Number(event.key));if(event.key==="Escape")document.querySelectorAll("dialog[open]").forEach(d=>d.close());});
const hashWord=decodeURIComponent(location.hash.slice(1));renderAll();renderExercise();syncSheet().then(()=>{if(hashWord){const found=words.find(item=>item.word.toLocaleLowerCase("fr")===hashWord.toLocaleLowerCase("fr"));if(found)startSession([found]);}});
